# Change these first
owner: inUtil-info # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: inUtil Labs
    url: https://inutil.info
  - name: gasolinBot
    check: "tcp-ping"
    url: mqin.inutil.info
    port: $GASOLIN_BOT_PORT
  - name: whin
    url: $WHIN_URL
  - name: monitorin
    url: $MONITORIN_URL
  - name: tarifin
    url: $TARIFIN_URL
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: mqin
    check: "tcp-ping"
    url: mqin.inutil.info
    port: $MQIN_PORT    
  - name: canalin
    url: $CANALIN_URL
  - name: hookin
    url: https://inutil.info
  - name: robotin
    check: "tcp-ping"
    url: mqin.inutil.info
    port: $ROBOTIN_PORT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.inutil.info
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/inUtil-info/status/master/assets/dado-ext.svg
  faviconSvg: https://raw.githubusercontent.com/inUtil-info/status/master/assets/dado-ext.svg
  name: inUtil Labs
  introTitle: "Real time state of **inUtil** micro-services."
  introMessage: 
  # This status page shows **real-time** data from our [GitHub repository](https://github.com/inUtin-info/status). No server is required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: light
  # customHeadHtml: "<link rel="shortcut icon" type="image/x-icon" href="https://inutil.info/favicon.ico?">"   (revisar esto, por algun motivo no va)
  navbar:
    #- title: Status
    #  href: /
    - title: GitHub
      href: https://github.com/inUtil-info
    - title: inUtil Labs
      href: https://inutil.info
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is [open source]($REPO).
  allSystemsOperational: "All micro-services are operational"
commitMessages:
  commitAuthorName: "inUtilBot"
  commitAuthorEmail: "info@inutil.info"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
