# Change these first
owner: inUtil-info # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: inUtil Labs
    url: https://inutil.info
  - name: gasolinBot
    url: https://en.wikipedia.org
  - name: whin
    url: https://news.ycombinator.com
  - name: monitorin
    url: https://inutil.info
  - name: tarifin
    url: https://inutil.info
  - name: mqin
    url: https://inutil.info
  - name: canalin
    url: https://inutil.info
  - name: hookin
    url: https://inutil.info
  - name: robotin
    url: https://inutil.info

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.inutil.info
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: inUtil Labs
  introTitle: "Real time status of **inUtil** micro-services."
  introMessage: 
  # This status page shows **real-time** data from our [GitHub repository](https://github.com/inUtin-info/status). No server is required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: night
  navbar:
    - title: Status
      href: /
    - title: inUtil Labs
      href: https://inutil.info
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
